"use client";

import { motion } from "motion/react";
import { Heart, Smartphone, Shield, Sparkles } from "lucide-react";
import type { LucideIcon } from "lucide-react";

interface Integration {
  icon: LucideIcon;
  name: string;
  description: string;
}

const integrations: Integration[] = [
  {
    icon: Heart,
    name: "Apple Health Sync",
    description:
      "Full bi-directional sync with Apple Health — vitals, activity, sleep, nutrition, and health records all in one place.",
  },
  {
    icon: Smartphone,
    name: "Built for iOS",
    description:
      "A native iOS experience with buttery-smooth performance, haptic feedback, and seamless system integration.",
  },
  {
    icon: Sparkles,
    name: "AI-Powered Engine",
    description:
      "Every insight is generated by our AI — trained on Olympic-level health data and peer-reviewed research.",
  },
  {
    icon: Shield,
    name: "Privacy First",
    description:
      "Your health data stays yours. End-to-end encryption, no third-party sharing, and full transparency on how your data is used.",
  },
];

export default function Integrations() {
  return (
    <section className="relative py-24 sm:py-32">
      {/* Decorative orbs */}
      <div className="pointer-events-none absolute inset-0" aria-hidden>
        <div className="absolute bottom-0 left-[10%] h-[350px] w-[350px] rounded-full bg-[#065b64]/8 blur-[100px]" />
        <div className="absolute top-10 right-[15%] h-[300px] w-[300px] rounded-full bg-[#EC7013]/8 blur-[100px]" />
      </div>

      <div className="relative mx-auto max-w-5xl px-6">
        {/* Header */}
        <div className="mb-16 text-center">
          <h2 className="text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl lg:text-5xl">
            The foundation behind every insight.
          </h2>
          <p className="mx-auto mt-4 max-w-md leading-relaxed text-slate-600">
            Olympic-tested science meets cutting-edge technology — built to keep
            your data safe and your health on track.
          </p>
        </div>

        {/* Cards */}
        <div className="grid gap-6 sm:grid-cols-2">
          {integrations.map((item, i) => (
            <motion.div
              key={item.name}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{
                duration: 0.5,
                delay: i * 0.1,
                ease: [0.16, 1, 0.3, 1],
              }}
              viewport={{ once: true }}
              className="group flex gap-5 rounded-[2rem] sm:rounded-[50px] border border-white/50 bg-white/30 p-7 shadow-[0_8px_32px_rgba(0,0,0,0.06),inset_0_1px_0_rgba(255,255,255,0.6)] backdrop-blur-2xl transition-all duration-300 hover:-translate-y-1 hover:shadow-[0_16px_48px_rgba(0,0,0,0.1),inset_0_1px_0_rgba(255,255,255,0.8)]"
            >
              <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-[#065b64] to-[#0a8f9c] text-white shadow-lg shadow-[#065b64]/20">
                <item.icon className="h-6 w-6" />
              </div>
              <div>
                <h3 className="font-bold text-slate-900">{item.name}</h3>
                <p className="mt-1.5 text-sm leading-relaxed text-slate-600">
                  {item.description}
                </p>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
